name: test_dio_and_api
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  connectivity: ^3.0.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
